# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Scouting the Statline 
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Scouting the Statline is a site of minor league comps.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.scoutingthestatline.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: twcunningham
github_username:  cunningt
minimal_mistakes_skin: contrast

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Michael Rose"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  email  : # optional
  uri    : "https://mademistakes.com"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

