title: Scouting the Statline
email: tom@scoutingthestatline.com
description: >- # this means to ignore newlines until "baseurl:"
  Scouting the Statline is an attempt to find minor league comps.
baseurl: /
url: https://www.scoutingthestatline.com
twitter_username: twcunningham
github_username: cunningt
minimal_mistakes_skin: dark

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Michael Rose"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  email  : # optional
  uri    : "https://www.scoutingthestatline.com"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
