# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Scouting the Statline 
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Scouting the statline is a site of minor league comps.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.scoutingthestatline.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: twcunningham
github_username:  cunningt

# Build settings
markdown: kramdown
theme: jekyll-theme-leap-day
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
